# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'CallGinie' do
   #pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga/Yoga.podspec'
   pod 'GoogleMaps' 
end
