# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'CallGinie' do
   #pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga/Yoga.podspec'
   pod 'GoogleMaps'  
  #pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'

end
