export const REGISTER="REGISTER";
export const REGISTER_ERROR="REGISTER_ERROR";
export const LOGIN_SUCCESS='LOGIN_SUCCESS';
export const LOGIN_FAIL='LOGIN_FAIL';


export const GET_SERVICE_LIST='GET_SERVICE_LIST';
export const GET_SERVICE_LIST_ERROR='GET_SERVICE_LIST_ERROR';