 export const REGISTER="REGISTER";
export const REGISTER_ERROR="REGISTER_ERROR";
export const LOGIN_SUCCESS='LOGIN_SUCCESS';
export const LOGIN_FAIL='LOGIN_FAIL';

export const IS_ALREADY_LOGGEDIN='IS_ALREADY_LOGGEDIN';

export const GET_SERVICE_LIST='GET_SERVICE_LIST';
export const GET_SERVICE_LIST_ERROR='GET_SERVICE_LIST_ERROR';


export const GET_WORKSHOP_SERVICE_LIST='GET_WORKSHOP_SERVICE_LIST';
export const  GET_WORKSHOP_SERVICE_LIST_ERROR='GET_WORKSHOP_SERVICE_LIST_ERROR';

export const ADD_WORKSHOP_SERVICES='ADD_WORKSHOP_SERVICES';
export const ADD_WORKSHOP_SERVICES_ERROR='ADD_WORKSHOP_SERVICES_ERROR';


export const BOOK_SERVICE='BOOK_SERVICE';
export const BOOK_SERVICE_ERROR='BOOK_SERVICE_ERROR';

export const SET_APPOINTMENT_DETAILS='SET_APPOINTMENT_DETAILS';
export const UPDATE_WORKSHOP_LOCATION='UPDATE_WORKSHOP_LOCATION';

export const MECHANIC_REACHED='MECHANIC_REACHED';
export const SET_RECEIPT='SET_RECEIPT';
export const END_SERVICE='END_SERVICE';

export const RESET_APPOINTMENT='RESET_APPOINTMENT'